### ISSUE TITLE
issue when migrating to 0.17.2

### ISSUE THREAD

**Issue by sansagara** [quantumblacklabs/kedro#726]
## Description
I can install release 0.17.2, however, I can not run any commands after I do it coming from 0.17.1.
New release seems to be unstable? 

## Context
Trying to create a new project or even display the version now fails!

## Steps to Reproduce
1. pip install kedro==0.17.2
2. kedro --version

## Expected Result
I should get the version printed. 

## Actual Result
However, I get:
```
File "/root/user_files/env/xpvu-kedro-starter/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/root/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 212, in main
    configure_project(package_name)
  File "/root/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/kedro/framework/project/__init__.py", line 171, in configure_project
    pipelines.configure(pipelines_module)
  File "/root/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages/kedro/framework/project/__init__.py", line 123, in configure
    project_pipelines = register_pipelines()
TypeError: register_pipelines() missing 1 required positional argument: 'self'
```

## Your Environment
kedro -V shows an error.
pip show kedro:
```
Name: kedro
Version: 0.17.2
Summary: Kedro helps you build production-ready data and analytics pipelines
Home-page: https://github.com/quantumblacklabs/kedro
Author: QuantumBlack Labs
Author-email: None
License: Apache Software License (Apache 2.0)
Location: /root/user_files/env/xpvu-kedro-starter/lib/python3.7/site-packages
Requires: pip-tools, toml, toposort, click, jupyter-client, anyconfig, PyYAML, cachetools, setuptools, jmespath, dynaconf, cookiecutter, python-json-logger, gitpython, pluggy, fsspec
Required-by:
```
* Python version used (`python -V`):
`Python 3.7.10`
* Operating system and version:
`CentOS7`

**Comment by limdauto** [comment]
Hi @sansagara there seems to be something in your project that isn't standard Kedro. Could you confirm that you can replicate this behaviour with a brand new project or with one of our starters?

**Comment by limdauto** [comment]
Hi @sansagara it seems like you are trying to run kedro commands in a directory that is a Kedro project and there is a file called `pipeline_registry.py`. Could you paste the content of that file here?

**Comment by sansagara** [comment]
You are very right dear @limdauto !! I see the issue now
When I tried to migrate from 0.17.0, I copied the register_pipelines method from `hooks.py` into `pipeline_registry.py`, however, I left the previous signature.

For `hooks.py`, it was:
```python
    def register_pipelines(self) -> Dict[str, Pipeline]:
```
However, now `pipeline_registry.py` expects it like:
```python
    def register_pipelines() -> Dict[str, Pipeline]:
```

So, as you can see, it's just a migration error. Thanks for your pointer:
PS: I'll edit the issue title to something more.... accurate ;)

**Comment by sansagara** [comment]
Also, I must also say the following: It's a bit counterintuitive that Kedro evaluates these kind of configurations even for commands such as `--version` or `new`, which actually don't relate to the working environment.
